### ISSUE TITLE
typoとか

### ISSUE THREAD

**Issue by taba2424** [calmato/web#15]
* [x] irestore -> Firestore (https://www.calmato.jp/gran_cook)

![スクリーンショット 2021-10-18 2 32 42](https://user-images.githubusercontent.com/27718413/137638421-747746c3-5983-4af9-aae3-26efa84924d8.png)

* [x] Technology StackのLanguage -> スペース入れる (https://www.calmato.jp/gran_cook)
    * 他はスペースが入ってるので

![スクリーンショット 2021-10-18 2 45 11](https://user-images.githubusercontent.com/27718413/137638774-736b3e00-11c9-43e0-9c65-82d6a3418726.png)

* [x] Server side engineer -> Backend engineer (https://www.calmato.jp/)
    * Frontend engineer の表記と合わせたい

![スクリーンショット 2021-10-18 2 45 28](https://user-images.githubusercontent.com/27718413/137638769-b47a949d-1fec-458c-978c-e19d7dc19ce7.png)

**Comment by hamachans** [comment]
修正しましたので、closeします
